### PR TITLE
/builder: clear the response panel when the query isn't ready

### LINKED ISSUE #197: /builder: clear the response panel when the query isn't ready
When a query isn't ready the builder should clear the response panel. That was normal behaviour until #179 which broke it

### PR DESCRIPTION
**Pull request by saabi**
Closes #197

- Fixed: The response panel now clears if the query isn't ready.

### CODE REVIEW

**Review by mindrones — DISMISSED** [review]
LGTM.

Unrelated to this PR, but since we're here:
- I'd move `setErrorStatus` to `Error.entry` and `setMatchingStatus` to `Matching.entry`
- I'd change from `onEntry` to `entry` everywhere

**Comment by mindrones** [comment]
Here's a glitch:
- Start here, works: https://deploy-preview-202--dapsboard-dev.netlify.app/builder/?q=(dataset:arxlive_arxiv_v6,form:primary,forms:!((name:primary,selection:(aggregation:missing,field:date_created_article,type:date)),(name:secondary)),size:0)
- deselect `date_created_article`: works (clears the response)
- select `date_created_article` again: no response, no console errors

**Comment by mindrones** [comment]
It works, but I'd try having `setNotReadyStatus` in `QueryReady.exit` as I think it would be semantically more correct.

**Comment by saabi** [comment]
> It works, but I'd try having `setNotReadyStatus` in `QueryReady.exit` as I think it would be semantically more correct.

You're right about that, and so obvious I should have caught it.

**Review by mindrones — APPROVED** [review]
Well done 👍

**Pull request merged**
