### PR TITLE
Replaced ES_keyword for ES_text_w_keyword on three fields

### LINKED ISSUE #146: Arxiv spec wrong type
fails: https://dapsboard-dev.netlify.app/builder/?q=(dataset:general_arxiv_v0,form:primary,forms:!((name:primary,selection:(aggregation:missing,field:type_of_entity,type:ES_text_w_keyword)),(name:secondary)),size:0)

works: https://dapsboard-dev.netlify.app/builder/?q=(dataset:general_arxiv_v0,form:primary,forms:!((name:primary,selection:(aggregation:missing,field:url_of_article,type:ES_text_w_keyword)),(name:secondary)),size:0)

Seems like a bug in the specs

### PR DESCRIPTION
**Pull request by saabi**
Closes #146

### CODE REVIEW

**Comment by mindrones** [comment]
The deploy is failing with `mkdirp: not found`

**Comment by saabi** [comment]
> The deploy is failing with `mkdirp: not found`

That's because of netlify using node 15. The fix for that is in #148 but this can be merged right away in any case.

**Comment by mindrones** [comment]
Let's port that here instead so that we can test the deploy

**Review by mindrones — APPROVED** [review]
Good to merge.

The remaining link mentioned in the issue [1] is still failing because `id_digitalObjectIdentifier_article` is indeed of type `ES_type` so `missing` should not be an available option and it will be tackled in #145.

[1] https://deploy-preview-165--dapsboard-dev.netlify.app/builder/?q=(dataset:arxlive_arxiv_v3,form:primary,forms:!((name:primary,selection:(aggregation:missing,field:id_digitalObjectIdentifier_article)),(name:secondary)),size:0)

**Pull request merged**
